#!/bin/sh
echo "------------------------------"
echo "updateall v.0.3 for Containers"
echo "------------------------------"

# Run this as a normal user. Your admin password will be asked for if required.

sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
echo "The script has now finished running."
