#!/bin/sh
echo "------------------------------"
echo "updateall v.0.3 for Containers"
echo "------------------------------"

# Run this as a normal user. Your admin password will be asked for if required.

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoremove -y
echo "The script has now finished running."
